# Generated by Django 2.2.1 on 2019-05-18 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superintendent', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(default=111, max_length=40, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
    ]
