# Generated by Django 2.2.1 on 2019-05-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superintendent', '0003_school_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('unit', models.IntegerField(choices=[(1, 'kg'), (2, 'l'), (3, 'szt'), (4, 'op.')])),
                ('calories', models.IntegerField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('carbo', models.FloatField(null=True)),
                ('calcium', models.IntegerField(null=True)),
                ('iron', models.FloatField(null=True)),
                ('vit_A', models.IntegerField(null=True)),
                ('vit_B1', models.FloatField(null=True)),
                ('vit_B2', models.FloatField(null=True)),
                ('vit_C', models.FloatField(null=True)),
                ('group', models.IntegerField(choices=[(1, 'Zbożowe'), (2, 'Mleczne'), (3, 'Jaja'), (4, 'Mięsne'), (5, 'Masło'), (6, 'Inne tłuszcze'), (7, 'Ziemniaki'), (8, 'Warz. i owoce z wit. C'), (9, 'Warz. i owoce z karot.'), (10, 'Inne warzywa i owoce'), (11, 'Strączkowe suche'), (12, 'Cukier i słodycze')], null=True)),
            ],
        ),
    ]
