# Generated by Django 2.2.1 on 2019-05-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superintendent', '0004_porducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porducts',
            new_name='Products',
        ),
    ]
