# Generated by Django 2.2.1 on 2019-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superintendent', '0005_auto_20190519_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField()),
                ('operation_type', models.IntegerField(choices=[(1, 'Przyjęcie'), (2, 'Wydanie')])),
                ('quantity', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=True, to='superintendent.Products')),
            ],
        ),
    ]
