# Generated by Django 2.2.1 on 2019-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superintendent', '0006_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.ManyToManyField(to='superintendent.Inventory'),
        ),
    ]
