# Generated by Django 2.2.1 on 2019-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superintendent', '0007_menu_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal_number', models.IntegerField(max_length=4)),
            ],
        ),
    ]
