# Generated by Django 2.2.1 on 2019-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superintendent', '0008_mealnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnumber',
            name='meal_number',
            field=models.IntegerField(),
        ),
    ]
