# Generated by Django 2.2.1 on 2019-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superintendent', '0009_auto_20190526_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnumber',
            name='meal_date',
            field=models.DateField(unique=True),
        ),
    ]
